parameters:
- name: stageName
  default: ''
- name: environment
  default: ''
- name: serviceConnection
  default: ''
- name: resourceGroupName
  default: ''
- name: region
  default: 'eastus'

stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stageName }}
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: ${{ parameters.environment }}
    variables:
    - name: parameterFile
      value: '@$(Pipeline.Workspace)/infrastructure/parameters/parameters.${{ parameters.environment }}.json'
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            displayName: Download infrastructure artifact
            artifact: infrastructure
        
          - task: AzureCLI@2
            displayName: Deploy infrastructure
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                DEPLOYMENT_NAME="data-factory-cd-$(date '+%F_%H_%M_%S')"
                echo "Using dpeloyment name $DEPLOYMENT_NAME"
                echo "Using parameter file $(parameterFile)"
                
                # Create the resource group
                az group create --location ${{ parameters.region }} --name ${{ parameters.resourceGroupName }}

                # Deploy Bicep template
                az deployment group create -g "${{ parameters.resourceGroupName }}" -n "$DEPLOYMENT_NAME" --template-file "$(Pipeline.Workspace)/infrastructure/maintemplate.bicep" --parameters "$(parameterFile)"
