trigger:
  branches:
    include:
    - adf_publish # Only run on changes to adf_publish

pr:
  branches:
    exclude:
    - '*' # Don't run on pull requests

stages:
- stage: Build
  jobs:
  - job:  Build
    displayName: Build infrastructure and publish artifacts
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: Build Bicep template
      inputs:
        azureSubscription: MSDN
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az bicep install
          az bicep build --file $(System.DefaultWorkingDirectory)/infrastructure/maintemplate.bicep

    - task: PublishPipelineArtifact@1
      displayName: Publish infrastructure artifact
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/infrastructure
        artifact: infrastructure
        publishLocation: pipeline

    - task: PublishPipelineArtifact@1
      displayName: Publish ADF artifact
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/data-factory
        artifact: data-factory
        publishLocation: pipeline

- template: templates/deploy.yaml
  parameters:
    stageName: DeployDevelopment
    environment: development
    serviceConnection: MSDN
    resourceGroupName: ADF-CI-CD-D
    region: eastus