trigger:
  branches:
    include:
    - adf_publish # Only run when ADF artifacts are published

pr:
  branches:
    exclude:
    - '*' # Don't run for PRs

stages:
- stage: Publish
  displayName: Publish ADF artifacts
  jobs:
  - job: Publish
    displayName: Publish ADF artifacts
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: PublishPipelineArtifact@1
      displayName: Publish ADF artifacts
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/cmhadfcicd-d/
        artifact: adf_publish
        publishLocation: pipeline
    
    - task: PublishPipelineArtifact@1
      displayName: Publish pre and post deploy script
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/.pipelines/scripts
        artifact: scripts
        publishLocation: pipeline

- template: templates/deploy-adf-artifacts.yaml
  parameters:
    stageName: DeployDevelopmentADFArtifacts
    environment: development
    serviceConnection: MSDN
    resourceGroupName: ADF-CI-CD-D
    dataFactoryName: cmhadfcicd-adf-d
    archiveStorageConnectionStringSecretName: DEST-STORAGE-CONNECTION-STRING
    orderStorageConnectionStringSecretName: SRC-STORAGE-CONNECTION-STRING
    keyVaultBaseUrl: https://cmhadfcicd-kv-d.vault.azure.net/
